swagger: "2.0"
info:
  description: "Documentation for a LogRhythm platform API"
  version: "v1.0.0"
  title: "My LogRhythm API"
x-servers:
  - url: "https://localhost:8501/lr-my-api"
    description: "Local API Gateway (https)"
schemes:
  - "http"
basePath: "/"
produces:
  - "application/json"
consumes:
  - "application/json"
host: "localhost:8501"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "Authenticate using a JSON Web Token (JWT)."
security:
    - Bearer: []
paths:
  /hello:
    get:
      summary: Get Hello
      description: Retrieve the current world greeting.
      operationId: getHelloWorld
      parameters:
        - $ref: "#/parameters/authHeader"
      responses:
        200:
          description: ok
    post:
      summary: Hello World
      description: Create a new greeting for the world.
      operationId: createHelloWorld
      parameters:
        - $ref: "#/parameters/authHeader"
      responses:
        201:
          description: ok
    delete:
      summary: Goodbye World
      description: Say goodbye to the world.
      operationId: deleteHelloWorld
      parameters:
        - $ref: "#/parameters/authHeader"
      responses:
        200:
          description: ok
parameters:
  authHeader:
    name: "Authorization"
    type: "string"
    in: "header"
    description: "Bearer authorization via a JSON Web Token (jwt)"
    required: true
